"""empty message

Revision ID: b556e430de5d
Revises: 12281cbc5bd1
Create Date: 2016-03-01 20:18:05.572270

"""

# revision identifiers, used by Alembic.
revision = 'b556e430de5d'
down_revision = '12281cbc5bd1'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
